POST https://criancaalfabetizada.caeddigital.net/portal/functions/getDadosResultado HTTP/1.1
content-type: application/json

{
  "CD_INDICADOR": [
    "11988LP14",
    "11988LP15",
    "11988LP16",
    "11988LP17",
    "11988LP18",
    "11988MT14",
    "11988MT15",
    "11988MT16",
    "11988MT17",
    "11988MT18",
    "61988LP14",
    "61988LP15",
    "61988LP16",
    "61988LP17",
    "61988LP18",
    "61988MT14",
    "61988MT15",
    "61988MT16",
    "61988MT17",
    "61988MT18",
    "71988LP14",
    "71988LP15",
    "71988LP16",
    "71988LP17",
    "71988LP18",
    "71988MT14",
    "71988MT15",
    "71988MT16",
    "71988MT17",
    "71988MT18",
    "12016LP14",
    "12016LP15",
    "12016LP16",
    "12016LP17",
    "12016LP18",
    "12016MT14",
    "12016MT15",
    "12016MT16",
    "12016MT17",
    "12016MT18",
    "62016LP14",
    "62016LP15",
    "62016LP16",
    "62016LP17",
    "62016LP18",
    "62016MT14",
    "62016MT15",
    "62016MT16",
    "62016MT17",
    "62016MT18",
    "72016LP14",
    "72016LP15",
    "72016LP16",
    "72016LP17",
    "72016LP18",
    "72016MT14",
    "72016MT15",
    "72016MT16",
    "72016MT17",
    "72016MT18"
  ],
  "agregado": "4306809",
  "filtros": [
    {
      "operation": "equalTo",
      "field": "DADOS.VL_FILTRO_AVALIACAO",
      "value": "AV22025"
    },
    {
      "operation": "equalTo",
      "field": "DADOS.VL_FILTRO_ETAPA",
      "value": "ENSINO FUNDAMENTAL DE 9 ANOS - 1º ANO"
    },
    {
      "operation": "equalTo",
      "field": "DADOS.VL_FILTRO_DISCIPLINA",
      "value": "LÍNGUA PORTUGUESA"
    }
  ],
  "filtrosAdicionais": [
    {
      "field": "DADOS.VL_FILTRO_REDE",
      "value": "PÚBLICA",
      "operation": "equalTo"
    }
  ],
  "nivelAbaixo": "1",
  "ordenacao": [
    [
      "NM_ENTIDADE",
      "ASC"
    ]
  ],
  "collectionResultado": null,
  "CD_INDICADOR_LABEL": [],
  "TP_ENTIDADE_LABEL": "01",
  "_ApplicationId": "portal",
  "_ClientVersion": "js2.19.0",
  "_InstallationId": "63e7d8d8-a570-42ba-a9af-8ce8bf044cf1",
  "_SessionToken": "r:e936f6f0d778e4447c34540e4aeb61a8"
}